#!/bin/sh
# tools/migration_baseline/gen_symbol_inventory.sh — M1.1 (#122) exported
# C symbol inventory, captured from the BUILT ARTIFACT with nm rather than
# transcribed from the header, so it can be rerun and diffed later (the
# issue's own acceptance rule for this row).
#
# What it does:
#   1. builds libmojito_sys.dylib via the repo's own Makefile if missing
#      or stale (so this is never run against a stale artifact);
#   2. runs `nm -gU` (defined, global/external symbols only) over it;
#   3. keeps only the mjs_* / ms_context_* prefixes (issue #122's own
#      scope: "the exported C symbol set (mjs_* plus ms_context_*)") and
#      strips the Mach-O leading underscore;
#   4. sorts the result for a stable diff.
#
# Modes:
#   (no args)   generate MOJO_MIGRATION_SYMBOLS.txt at the repo root
#               (overwrites it).
#   --check     regenerate into a throwaway temp file and diff it against
#               the committed MOJO_MIGRATION_SYMBOLS.txt; exits non-zero
#               (and prints the diff) on ANY mismatch, including the file
#               not existing yet. This is the RED-first verification mode:
#               it fails until the file has been generated and committed,
#               and it fails again the moment the built symbol set drifts
#               from what is committed (a later native/ change, or the
#               ABI shrinking as Phase 2 lands Mojo replacements).
#
# Usage:
#   tools/migration_baseline/gen_symbol_inventory.sh [--check]
#     CC=<cc>   override the compiler (passed through to `make`)

set -u

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
REPO_ROOT=$(CDPATH= cd -- "$SCRIPT_DIR/../.." && pwd)
DYLIB="$REPO_ROOT/libmojito_sys.dylib"
OUT="$REPO_ROOT/MOJO_MIGRATION_SYMBOLS.txt"
MODE=${1:-generate}

if ! command -v nm >/dev/null 2>&1; then
    echo "gen_symbol_inventory: nm not found on PATH"
    exit 2
fi

if [ ! -f "$DYLIB" ]; then
    echo "== building $DYLIB"
    if ! make -C "$REPO_ROOT" libmojito_sys.dylib >/dev/null 2>&1; then
        echo "gen_symbol_inventory: \`make libmojito_sys.dylib\` failed"
        exit 2
    fi
fi

TMP=$(mktemp 2>/dev/null) || { echo "gen_symbol_inventory: mktemp failed"; exit 2; }
trap 'rm -f "$TMP"' EXIT

{
    echo "# mojito-sys exported C symbol inventory (issue #122)."
    echo "# Generated by tools/migration_baseline/gen_symbol_inventory.sh"
    echo "# from libmojito_sys.dylib via \`nm -gU\`; do not hand-edit."
    echo "# Rerun the script (no args) to regenerate after a native/ change."
    echo "#"
    nm -gU "$DYLIB" 2>/dev/null \
        | awk '{print $3}' \
        | sed 's/^_//' \
        | grep -E '^(mjs_|ms_context_)' \
        | sort
} >"$TMP"

n=$(grep -vc '^#' "$TMP")

if [ "$MODE" = "--check" ]; then
    if [ ! -f "$OUT" ]; then
        echo "gen_symbol_inventory: --check FAIL — $OUT does not exist yet"
        echo "   (regenerated $n symbols; run without --check to commit them)"
        exit 1
    fi
    if ! diff -u "$OUT" "$TMP" >"$TMP.diff" 2>&1; then
        echo "gen_symbol_inventory: --check FAIL — committed inventory drifted"
        echo "   from what the built dylib actually exports:"
        sed 's/^/    | /' "$TMP.diff"
        rm -f "$TMP.diff"
        exit 1
    fi
    rm -f "$TMP.diff"
    echo "gen_symbol_inventory: --check PASS ($n symbols, matches $OUT)"
    exit 0
fi

cp "$TMP" "$OUT"
echo "gen_symbol_inventory: wrote $n symbols to $OUT"
exit 0
