#!/bin/sh
# tools/migration_baseline/run_alloc_counts.sh — build + run the SYS-4
# allocation-counting harness (issue #122: "allocation counts are measured,
# not asserted") and commit its output.
#
# Builds:
#   1. alloc_probe_shim.dylib — a dyld-interposing malloc/calloc/realloc/
#      free counter (macOS only — see alloc_probe_shim.c);
#   2. alloc_count_fastpaths — a driver that calls each fast path
#      native/include/mojito_sys.h documents as SYS-4 (or allocation-free
#      once its handle exists) N times and reports the delta.
#
# Modes:
#   (no args)   run and write MOJO_MIGRATION_ALLOC_COUNTS.tsv at the repo
#               root (machine-parseable: name\titerations\talloc_calls\t
#               free_calls\tnote).
#   --check     rerun into a temp file and diff against the committed
#               MOJO_MIGRATION_ALLOC_COUNTS.tsv (RED before this issue
#               lands real numbers, and again if native/ changes the
#               allocation behavior of a measured primitive later).
#
# Usage: tools/migration_baseline/run_alloc_counts.sh [--check]
#   CC=<cc> override the compiler.

set -u

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
REPO_ROOT=$(CDPATH= cd -- "$SCRIPT_DIR/../.." && pwd)
CC=${CC:-cc}
DYLIB="$REPO_ROOT/libmojito_sys.dylib"
BUILD="$REPO_ROOT/build/migration_baseline"
SHIM="$BUILD/alloc_probe_shim.dylib"
DRIVER="$BUILD/alloc_count_fastpaths"
OUT="$REPO_ROOT/MOJO_MIGRATION_ALLOC_COUNTS.tsv"
MODE=${1:-generate}

case "$(uname -s)" in
    Darwin) ;;
    *)
        echo "run_alloc_counts: dyld interposing (this harness) is macOS-only;"
        echo "   this is the reference host for the whole baseline anyway."
        exit 2
        ;;
esac

if [ ! -f "$DYLIB" ]; then
    echo "== building $DYLIB"
    if ! make -C "$REPO_ROOT" libmojito_sys.dylib >/dev/null 2>&1; then
        echo "run_alloc_counts: \`make libmojito_sys.dylib\` failed"
        exit 2
    fi
fi

mkdir -p "$BUILD"
if ! "$CC" -dynamiclib -O0 -g "$SCRIPT_DIR/alloc_probe_shim.c" -o "$SHIM" 2>"$BUILD/shim.err"; then
    echo "run_alloc_counts: shim build failed:"
    sed 's/^/    | /' "$BUILD/shim.err"
    exit 2
fi
if ! "$CC" -Wall -Wextra -O0 -g -I"$REPO_ROOT/native/include" \
        "$SCRIPT_DIR/alloc_count_fastpaths.c" "$DYLIB" -o "$DRIVER" 2>"$BUILD/driver.err"; then
    echo "run_alloc_counts: driver build failed:"
    sed 's/^/    | /' "$BUILD/driver.err"
    exit 2
fi

TMP=$(mktemp 2>/dev/null) || { echo "run_alloc_counts: mktemp failed"; exit 2; }
RAW=$(mktemp 2>/dev/null) || { echo "run_alloc_counts: mktemp failed"; exit 2; }
trap 'rm -f "$TMP" "$TMP.diff" "$RAW"' EXIT

if ! DYLD_INSERT_LIBRARIES="$SHIM" DYLD_FORCE_FLAT_NAMESPACE=1 \
        DYLD_LIBRARY_PATH="$REPO_ROOT" "$DRIVER" >"$RAW" 2>"$BUILD/run.err"; then
    echo "run_alloc_counts: driver exited nonzero:"
    sed 's/^/    | /' "$BUILD/run.err"
    cat "$BUILD/run.err" >&2
    exit 2
fi

{
    echo "# mojito-sys SYS-4 fast-path allocation counts (issue #122)."
    echo "# Generated by tools/migration_baseline/run_alloc_counts.sh via"
    echo "# alloc_probe_shim.c (dyld interposing malloc/calloc/realloc/free"
    echo "# counter) + alloc_count_fastpaths.c; do not hand-edit."
    echo "# host: $(uname -s)/$(uname -m)/$(uname -r)"
    echo "#"
    echo "# name	iterations	alloc_calls_total	free_calls_total"
    grep '^ALLOC_COUNT	' "$RAW" | cut -f2-
} >"$TMP"

n=$(grep -vc '^#' "$TMP")

if [ "$n" -eq 0 ]; then
    echo "run_alloc_counts: driver produced no ALLOC_COUNT rows:"
    sed 's/^/    | /' "$RAW"
    exit 2
fi

if [ "$MODE" = "--check" ]; then
    if [ ! -f "$OUT" ]; then
        echo "run_alloc_counts: --check FAIL — $OUT does not exist yet"
        echo "   (regenerated $n rows; run without --check to commit them)"
        exit 1
    fi
    if ! diff -u "$OUT" "$TMP" >"$TMP.diff" 2>&1; then
        echo "run_alloc_counts: --check FAIL — committed counts drifted:"
        sed 's/^/    | /' "$TMP.diff"
        exit 1
    fi
    echo "run_alloc_counts: --check PASS ($n rows, matches $OUT)"
    exit 0
fi

cp "$TMP" "$OUT"
echo "run_alloc_counts: wrote $n rows to $OUT"
exit 0
